CREATE TABLE IF NOT EXISTS auteur (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nom             VARCHAR(255),
    prenom          VARCHAR(255),
    nationalite     VARCHAR(255),
    date_naissance  DATE,
    date_deces      DATE,
    CONSTRAINT pk_auteur PRIMARY KEY (id)
);


ALTER TABLE livre
    DROP COLUMN IF EXISTS auteur,
    ADD COLUMN IF NOT EXISTS auteur_id INTEGER;

ALTER TABLE livre
    ADD CONSTRAINT fk_livre_auteur
    FOREIGN KEY (auteur_id) REFERENCES auteur(id);